name: sky-vm

file_mounts:
  /datasets:
    source: s3://asf-daps
    store: s3 
    mode: MOUNT

setup: |
  sudo apt-get update -y && apt-get install build-essential -y
  sudo apt-get install git-crypt direnv curl autoconf automake libtool pkg-config -y
  git clone https://github.com/nestauk/asf_exploration.git
  cd asf_exploration
  git checkout 19-compare-core-with-daps-outputs
  git pull
  cd compare_core_with_daps_outputs


  # On Linux it's probably a good idea to run
  sudo ldconfig

  pip install --upgrade pip
  conda init bash
  conda config --remove channels https://aws-ml-conda-ec2.s3.us-west-2.amazonaws.com
  conda create -n compare_core_daps python=3.9
  conda activate compare_core_daps
  pip install -r requirements.txt

run: |
  cd ~/sky_workdir
  conda deactivate
  conda activate compare_core_daps
  jupyter notebook --no-browser --port 8888
  