common_cols: ['BUILDING_REFERENCE_NUMBER',
 'ADDRESS1',
 'ADDRESS2',
 'POSTCODE',
 'INSPECTION_DATE',
 'ENERGY_CONSUMPTION_CURRENT',
 'TOTAL_FLOOR_AREA',
 'CURRENT_ENERGY_EFFICIENCY',
 'CURRENT_ENERGY_RATING',
 'POTENTIAL_ENERGY_RATING',
 'CO2_EMISS_CURR_PER_FLOOR_AREA',
 'WALLS_DESCRIPTION',
 'WALLS_ENERGY_EFF',
 'ROOF_DESCRIPTION',
 'ROOF_ENERGY_EFF',
 'FLOOR_DESCRIPTION',
 'FLOOR_ENERGY_EFF',
 'WINDOWS_DESCRIPTION',
 'WINDOWS_ENERGY_EFF',
 'MAINHEAT_DESCRIPTION',
 'MAINHEAT_ENERGY_EFF',
 'MAINHEATC_ENERGY_EFF',
 'SECONDHEAT_DESCRIPTION',
 'HOTWATER_DESCRIPTION',
 'HOT_WATER_ENERGY_EFF',
 'LIGHTING_DESCRIPTION',
 'LIGHTING_ENERGY_EFF',
 'CO2_EMISSIONS_CURRENT',
 'CONSTRUCTION_AGE_BAND',
 'LOW_ENERGY_LIGHTING',
 'FLOOR_LEVEL',
 'GLAZED_AREA',
 'NUMBER_HABITABLE_ROOMS',
 'NUMBER_HEATED_ROOMS',
 'LOCAL_AUTHORITY_LABEL',
 'MAINS_GAS_FLAG',
 'MAIN_HEATING_CONTROLS',
 'ENERGY_TARIFF',
 'MULTI_GLAZE_PROPORTION',
 'GLAZED_TYPE',
 'PHOTO_SUPPLY',
 'SOLAR_WATER_HEATING_FLAG',
 'TENURE',
 'TRANSACTION_TYPE',
 'BUILT_FORM',
 'PROPERTY_TYPE',
 'COUNTRY',
 'WALLS_ENERGY_EFF_SCORE',
 'ROOF_ENERGY_EFF_SCORE',
 'FLOOR_ENERGY_EFF_SCORE',
 'WINDOWS_ENERGY_EFF_SCORE',
 'MAINHEAT_ENERGY_EFF_SCORE',
 'MAINHEATC_ENERGY_EFF_SCORE',
 'HOT_WATER_ENERGY_EFF_SCORE',
 'LIGHTING_ENERGY_EFF_SCORE',
 'UPRN',
 'BUILDING_ADDRESS_ID',
 'N_SAME_UPRN_ENTRIES',
 'HEATING_SYSTEM',
 'HP_INSTALLED',
 'HEATING_FUEL',
 'HP_TYPE',
 'CURR_ENERGY_RATING_NUM',
 'ENERGY_RATING_CAT',
 'DIFF_POT_ENERGY_RATING']
